name: "Cache"
on:
  pull_request:
  push:
    branches:
      - "develop"
      - "feature/ci"

concurrency:
  group: ${{ github.ref }}-cache
  cancel-in-progress: true

jobs:
  packages:
    name: Cache OTP Derivations
    strategy:
      # Match support range of latest Elixir
      # https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
      matrix:
        elixir:
          - "1.13.4"
          - "1.14.5"
          - "1.15.3"
        # TODO: Enable MacOS when ARM chips are available
        os: [ubuntu-latest]
        otp:
          - "24.3.4.13"
          - "25.3.2.4"
          - "26.0.2"
        exclude:
          - elixir: "1.13.4"
            otp: "26.0.2"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          diagnostic-endpoint: ""
      - uses: DeterminateSystems/magic-nix-cache-action@v2
        with:
          diagnostic-endpoint: ""
      - uses: cachix/cachix-action@v12
        if: github.ref == 'refs/heads/develop'
        with:
          name: shanesveller-nix-beam-flakes
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pathsToPush: "./result"
          skipAddingSubstituter: true
      - run: |
          printf \
            "elixir %s\nerlang %s" \
              ${{ matrix.elixir }} \
              ${{ matrix.otp }} \
            | tee ./dev/example/.tool-versions
      - run: nix -L build .#example
