on:
  push:
    branches:
      - "develop"
jobs:
  publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          diagnostic-endpoint: ""
      - uses: DeterminateSystems/flakehub-push@671877163e61180aca1f99ba5c66ef266ce7983d
        with:
          visibility: "public"
          rolling: true
